on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: unit tests
      uses: colbyhill21/angular-full-ci/@v1.0
      with:
        testcommand: run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

#    - name: e2e tests
#      uses: colbyhill21/angular-full-ci/@v1.0
#      with:
#        testcommand: run e2e -- --protractor-config=e2e/protractor-ci.conf.js
